FORMAT: 1A
HOST: https://signature-api.herokuapp.com

# signature-api

API platform for signing documents.

The signature-api is based on [CONTRA]() API design. [JSON](http://www.json.org) is returned in all responses from the API, including errors.

I've tried to make it as easy to use as possible, but if you have any feedback please [let me know](mailto:mot@mot.la).

## GET /api/v0/documents/create.json?url={url}

Create a signable document. Allows for POST or GET.

+ Parameters
  + url (required, string, `http://mot.la/assets/resume.pdf`) ... String `url` of the PDF to convert.

+ Response 200 (application/json)

    {
      "documents": [{
        "pages": [ ],
        "status": "processing",
        "url": "http://motdotla.com/assets/resume.pdf",
        "share_url": "https://signature-share.herokuapp.com/?document_url=https://signature-api.herokuapp.com/api/v0/documents/f67b5764-5e13-4d37-af56-414e746ecafa.json"
      }]
    }

+ Response 400 (application/json)

    {
      "errors": [{
        "code": "required",
        "field": "url",
        "message": "url cannot be blank"
      }]
    }

## GET /api/v0/documents/{id}

Get a signable document. 

+ Parameters
  + id (rqeuired, string, `1`) ... String `id` of the PDF.

+ Response 200 (application/json)

    {
      "documents": [{
        "pages": [{
          "number": 1,
          "url": "https://carvedevelopment.s3.amazonaws.com/87911158-edbc-488b-6e60-960d67809107/1.png"
        }],
        "status": "processing",
        "url": "http://motdotla.com/assets/resume.pdf",
        "share_url": "https://signature-share.herokuapp.com/?document_url=https://signature-api.herokuapp.com/api/v0/documents/f67b5764-5e13-4d37-af56-414e746ecafa.json"
      }]
    } 

+ Response 400 (application/json)

    {
      "errors": [{
        "code": "not_found",
        "field": "id",
        "message": "id could not be found"
      }]
    }

## GET /api/v0/signature_elements/create.json?x={x}&y={y}&url={url}&page_number={page_number}

Create a signature_element in a signing. Allows for POST or GET.

+ Parameters
  + x (required, string, `20`) ... String `x` position of the element.
  + y (required, string, `20`) ... String `y` position of the element.
  + url (required, string, `somedataurl`) ... String `url` as a data url image of the signature.
  + page_number (required, string, `1`) ... String `page_number` of the element.

+ Response 200 (application/json)

    {
      "signature_elements": [{
        "x": 20,
        "y": 20,
        "url": "somedataurl",
        "page_number": 1
      }]
    }

+ Response 400 (application/json)

    {
      "errors": [{
        "code": "required",
        "field": "x",
        "message": "x cannot be blank"
      }]
    }

